version: '3'

services:

  postgresql:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./resources/docker-init-db.sql:/docker-entrypoint-initdb.d/docker-init-db.sql
    environment:
      - POSTGRES_DB=vault_demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=UTC

  vault:
    image: vault:1.3.0
    ports:
      - "8200:8200"
    volumes:
      - ./resources/vault_config.hcl:/vault/config/vault_config.hcl
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=0f55f2f0-4e78-4331-8597-5b4f0abbcd08
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - SKIP_SETCAP=true
      - disable_mlock=true

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  consul:
    image: consul
    ports:
     - 8500:8500