CREATE TABLE CREDIT_CARD (
  CREDIT_CARD_ID varchar(50) NOT NULL PRIMARY KEY,
  NUMBER varchar(100) NOT NULL,
  HOLDER varchar(60) NOT NULL,
  EXPIRATION_DATE DATE NOT NULL,
  BRAND varchar(50) NOT NULL,
  BIN CHAR(6) NOT NULL,
  LAST_DIGITS CHAR(4) NOT NULL,
  CREATED TIMESTAMP WITH TIME ZONE NOT NULL,
  UPDATED TIMESTAMP WITH TIME ZONE
);